import type { SportAssessment } from '@/sports/types';

/**
 * Basketball assessments.
 * The Initial Assessment (10 challenges, one per skill) is what every new
 * athlete runs during onboarding — it drives the ELO reveal.
 * Hurdles are post-calibration assessments unlocked by rating bands.
 */

export const basketballAssessments: SportAssessment[] = [
  {
    id: 'bb-assessment-initial',
    code: 'initial',
    title: 'Initial Assessment',
    description: 'Ten challenges across every skill. This sets your starting SPRINT rating.',
    difficulty: 'beginner',
    minutes: 15,
    isInitial: true,
    premium: false,
    challenges: [
      {
        skillCode: 'shooting',
        title: 'Spot-Up Shooting',
        description: 'Make as many of 10 spot-up shots from the free-throw line.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 1050,
        benchmarkLabel: 'Makes out of 10',
      },
      {
        skillCode: 'handling',
        title: 'Crossover Count',
        description: 'Crossover as many times as you can in 30 seconds without losing control.',
        metric: 'reps',
        attempts: 1,
        performanceOf: (attempts) => Math.min(1, attempts[0]! / 45),
        difficultyRating: 1000,
        benchmarkLabel: 'Crossovers in 30s',
      },
      {
        skillCode: 'finishing',
        title: 'Weak-Hand Layups',
        description: 'Convert as many weak-hand layups as you can out of 10.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 1000,
        benchmarkLabel: 'Makes out of 10',
      },
      {
        skillCode: 'passing',
        title: 'Chest Pass Accuracy',
        description: 'Hit a target chest-high from 15 feet. 10 attempts.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 950,
        benchmarkLabel: 'Hits out of 10',
      },
      {
        skillCode: 'defense',
        title: 'Defensive Slides',
        description: 'Slides across the width of the key 4 times without crossing your feet.',
        metric: 'reps',
        attempts: 4,
        performanceOf: (attempts) => attempts[0]! / 4,
        difficultyRating: 950,
        benchmarkLabel: 'Clean slides',
      },
      {
        skillCode: 'speed',
        title: 'Full-Court Sprint',
        description: 'One sprint, full court, against the clock. 8s = 100%.',
        metric: 'seconds',
        attempts: 1,
        performanceOf: (attempts) => Math.max(0, Math.min(1, (8 - attempts[0]!) / 3 + 0.33)),
        difficultyRating: 1000,
        benchmarkLabel: 'Seconds',
      },
      {
        skillCode: 'agility',
        title: '5-10-5 Shuttle',
        description: 'One clean 5-10-5 shuttle. Beat 6.5s for 100%.',
        metric: 'seconds',
        attempts: 1,
        performanceOf: (attempts) => Math.max(0, Math.min(1, (6.5 - attempts[0]!) / 2.5 + 0.5)),
        difficultyRating: 1000,
        benchmarkLabel: 'Seconds',
      },
      {
        skillCode: 'explosiveness',
        title: 'Standing Broad Jump',
        description: 'Best of 3 attempts. 2.4m = 100%.',
        metric: 'distance',
        attempts: 3,
        performanceOf: (attempts) => Math.min(1, Math.max(...attempts) / 2.4),
        difficultyRating: 1000,
        benchmarkLabel: 'Best jump (m)',
      },
      {
        skillCode: 'reaction',
        title: 'Reaction Clock',
        description: 'Respond to 5 visual cues; average response under 0.4s = 100%.',
        metric: 'seconds',
        attempts: 5,
        performanceOf: (attempts) => {
          const avg = attempts.reduce((a, b) => a + b, 0) / attempts.length;
          return Math.max(0, Math.min(1, (0.4 - avg) / 0.2 + 0.5));
        },
        difficultyRating: 1000,
        benchmarkLabel: 'Avg reaction (s)',
      },
      {
        skillCode: 'decision',
        title: 'Read the Game',
        description: '6 scripted reads — choose the right play before the cue ends.',
        metric: 'reps',
        attempts: 6,
        performanceOf: (attempts) => attempts[0]! / 6,
        difficultyRating: 1000,
        benchmarkLabel: 'Correct reads',
      },
    ],
  },
  {
    id: 'bb-assessment-hurdle-1200',
    code: 'hurdle-1200',
    title: 'Competitive Hurdle',
    description: 'Raise the bar on the five skills that decide games. Unlocks at 1200.',
    difficulty: 'intermediate',
    minutes: 12,
    isInitial: false,
    premium: false,
    challenges: [
      {
        skillCode: 'shooting',
        title: 'Spot-Up Threes',
        description: '10 attempts from above the break.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 1400,
        benchmarkLabel: 'Makes out of 10',
      },
      {
        skillCode: 'handling',
        title: 'Pressure Weave',
        description: 'Cone weave with a defender mirroring you — 20 touches clean.',
        metric: 'reps',
        attempts: 1,
        performanceOf: (attempts) => Math.min(1, attempts[0]! / 20),
        difficultyRating: 1350,
        benchmarkLabel: 'Clean touches',
      },
      {
        skillCode: 'finishing',
        title: 'Contact Finishes',
        description: 'Finish through a pad 6 times out of 10.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 1400,
        benchmarkLabel: 'Makes out of 10',
      },
      {
        skillCode: 'defense',
        title: 'Live Stops',
        description: 'Five 1v1 possessions — get a stop on at least 3.',
        metric: 'reps',
        attempts: 5,
        performanceOf: (attempts) => attempts[0]! / 5,
        difficultyRating: 1350,
        benchmarkLabel: 'Stops out of 5',
      },
      {
        skillCode: 'decision',
        title: '2v1 Reads',
        description: '10 live 2v1 reps — pass, drive or pull based on the defense.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 1400,
        benchmarkLabel: 'Correct reads',
      },
    ],
  },
  {
    id: 'bb-assessment-hurdle-1600',
    code: 'hurdle-1600',
    title: 'Elite Hurdle',
    description: 'The full gauntlet — timing, touch and toughness. Unlocks at 1600.',
    difficulty: 'advanced',
    minutes: 22,
    isInitial: false,
    premium: true,
    challenges: [
      {
        skillCode: 'shooting',
        title: 'Off-Dribble Gauntlet',
        description: '10 pull-ups off one-and-two dribble moves.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 1650,
        benchmarkLabel: 'Makes out of 10',
      },
      {
        skillCode: 'handling',
        title: 'Dark-Zone Marathon',
        description: '90 seconds, zero dribble violations, min 40 touches.',
        metric: 'seconds',
        attempts: 1,
        performanceOf: (attempts) => Math.min(1, attempts[0]! / 90),
        difficultyRating: 1650,
        benchmarkLabel: 'Seconds clean',
      },
      {
        skillCode: 'finishing',
        title: 'Rim Attack Series',
        description: '10 finishes vs two closing defenders.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 1700,
        benchmarkLabel: 'Makes out of 10',
      },
      {
        skillCode: 'defense',
        title: 'Denial Defense',
        description: '3 possessions of full denial — allow zero catches.',
        metric: 'reps',
        attempts: 3,
        performanceOf: (attempts) => attempts[0]! / 3,
        difficultyRating: 1700,
        benchmarkLabel: 'Denials out of 3',
      },
      {
        skillCode: 'decision',
        title: 'Blitz Reads',
        description: '10 possessions vs a blitzing defense — punish every mistake.',
        metric: 'reps',
        attempts: 10,
        performanceOf: (attempts) => attempts[0]! / 10,
        difficultyRating: 1750,
        benchmarkLabel: 'Correct reads',
      },
    ],
  },
];

export const basketballInitialAssessment = basketballAssessments.find(
  (a) => a.isInitial,
)!;

export function basketballAssessmentById(id: string): SportAssessment | undefined {
  return basketballAssessments.find((a) => a.id === id);
}